[package]
name = "tolliver-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
# Tolliver (obviously)
tolliver = { path = "../tolliver" }
# Logging
log = "0.4"
# ProtoBufs
prost = "0.13"

[build-dependencies]
prost-build = "0.13"
