[package]
name = "tolliver-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
# Tolliver (obviously)
tolliver = { path = "../tolliver" }
# ProtoBufs (using this instead of prost because it supports reflection)
protobuf = "3.7"
protobuf-parse = "3.7"

