[package]
name = "tolliver"
version = "0.1.0"
edition = "2021"

[dependencies]
# Logging
log = "0.4.27"
# ProtoBufs
prost = "0.14.1"
# SQL
rusqlite = "0.37.0"

[build-dependencies]
prost-build = "0.14.1"
